POST https://localhost:1001/api/user/login
Content-Type: application/json

{
  "login": "login2",
  "password": "pass2"
}

###

POST https://localhost:1001/api/user/registration
Content-Type: application/json

{
  "login": "login2",
  "password": "pass2"
}


###